export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const FETCH_PRODUCTS_FAIL = 'FETCH_PRODUCTS_FAIL';

export const DELETE_FROM_CART = 'DELETE_FROM_CART';

// export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS';
// export const ADD_TO_CART_FAIL = 'ADD_TO_CART_FAIL';

export const FETCH_CART_FROM_LOCAL_STORE = 'FETCH_CART_FROM_LOCAL_STORE';
export const FETCH_CART_FROM_LOCAL_FAIL = 'FETCH_CART_FROM_LOCAL_FAIL';