export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const FETCH_PRODUCTS_FAIL = 'FETCH_PRODUCTS_FAIL';

export const DELETE_FROM_CART = 'DELETE_FROM_CART';

export const CART_COUNTER = 'CART_COUNTER';

// export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS';
// export const ADD_TO_CART_FAIL = 'ADD_TO_CART_FAIL';

export const FETCH_CART_FROM_LOCAL_STORE = 'FETCH_CART_FROM_LOCAL_STORE';
export const FETCH_CART_FROM_LOCAL_FAIL = 'FETCH_CART_FROM_LOCAL_FAIL';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';